version: "3.8"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: P@ssword1234
      MYSQL_DATABASE: test
      MYSQL_USER: makerz
      MYSQL_PASSWORD: P@ssword1234
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  api:
    build: .
    environment:
      DB_HOST: db
      DB_USER: makerz
      DB_PASSWORD: P@ssword1234
      DB_DATABASE: test
      APP_VERSION: 1.0.2
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
