version: '3.8'

services:
  ### DATABASE - MySQL ###
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssword1234
      MYSQL_DATABASE: test
      MYSQL_USER: makerz
      MYSQL_PASSWORD: P@ssword1234
    ports:
      - "3306:3306"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

  ### MQTT Broker - EMQX ###
  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    restart: always
    ports:
      - "1883:1883"   # MQTT
      - "8083:8083"   # MQTT over WebSocket
      - "8081:8081"   # EMQX Dashboard
      - "18083:18083" # External Dashboard Access
      - "8883:8883"   # Secure MQTT (Optional)
    environment:
      EMQX_ALLOW_ANONYMOUS: "true"
    networks:
      - mynetwork

  ### Node-RED ###
  node-red:
    image: nodered/node-red
    container_name: node-red
    restart: always
    ports:
      - "1880:1880" # External Dashboard Access
    volumes:
      - node_red_data:/data
    networks:
      - mynetwork

  ### Backend - Node.js API ###
  backend:
    build: ./backend
    container_name: backend
    restart: always
    depends_on:
      - mysql
      - emqx
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: makerz
      MYSQL_PASSWORD: P@ssword1234
      MYSQL_DATABASE: test
      MQTT_BROKER: mqtt://emqx
    networks:
      - mynetwork

  ## Frontend - Ionic ###
  frontend:
    image: nginx:alpine
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - mynetwork

volumes:
  mysql_data:
  node_red_data:

networks:
  mynetwork:
    driver: bridge
