version: '3.8'

services:
  ### DATABASE - MySQL ###
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssword1234
      MYSQL_DATABASE: test
      MYSQL_USER: makerz
      MYSQL_PASSWORD: P@ssword1234
    ports:
      - "3306:3306"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - ./db-data:/var/lib/mysql
    networks:
      - mynetwork

  ### DATABASE - MongoDB ###
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: mongod --wiredTigerCacheSizeGB 2
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: P@ssword1234

  ### MQTT Broker - EMQX ###
  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    restart: always
    ports:
      - "1883:1883"   # MQTT
      - "8083:8083"   # MQTT over WebSocket
      - "8081:8081"   # EMQX Dashboard
    environment:
      EMQX_ALLOW_ANONYMOUS: "true"

  ### Node-RED ###
  node-red:
    image: nodered/node-red
    container_name: node-red
    restart: always
    ports:
      - "1880:1880"
    volumes:
      - node_red_data:/data

  ### Backend - Node.js API ###
  backend:
    build: ./backend
    container_name: backend
    restart: always
    depends_on:
      - mysql
      - mongo
      - emqx
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
      MYSQL_DATABASE: device_db
      MONGO_URI: mongodb://root:P@ssword1234@mongo:27017/device_logs?authSource=admin
      MQTT_BROKER: mqtt://emqx

  ## Frontend - Ionic ###
  frontend:
    image: nginx:alpine
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  mysql_data:
  mongo_data:
  node_red_data:

networks:
  mynetwork:
    driver: bridge