version: "3.9"

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: P@ssword1234
      MYSQL_DATABASE: test
      MYSQL_USER: makerz
      MYSQL_PASSWORD: P@ssword1234
    #   # กำหนดค่า default-authentication-plugin
    #   MYSQLD_OPTS: "--default-authentication-plugin=mysql_native_password"
    # command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - ./db-data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - mynetwork

  api:
    build: .
    environment:
      DB_HOST: db
      DB_USER: makerz
      DB_PASSWORD: P@ssword1234
      DB_DATABASE: test
    ports:
      - '5000:5000'
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge